os: 'windows'
db:
  path: mongodb://121.138.223.128/etrade #mongodb://183.98.70.23/etrade #'mongodb://localhost/etrade' #'mongodb://lmo0317.iptime.org/etrade'
cron:
  FIND_TRADING : '30 */10 9-18 * * *'
