os: 'windows'
db:
  path: mongodb://183.98.70.23/etrade #mongodb://183.98.70.23/etrade  #mongodb://127.0.0.1/etrade
redis:
  path: 183.98.70.23
  port: 6379
cron:
  FIND_TRADING_TIME :
    TIME: '30 */1 9-16 * * 1-5'
  SEND_TRADING_FAVORITE : '0 */1 9-16 * * 1-5'
log:
  level: 'low' #high: everything log save, middle: eventlog, error log save, low: error log save