os: 'windows'
db:
  path: mongodb://183.98.70.23/etrade #mongodb://183.98.70.23/etrade #'mongodb://localhost/etrade' #'mongodb://lmo0317.iptime.org/etrade'
cron:
  FIND_TRADING : '30 */20 9-18 * * 1-5'
