os: 'windows'
db:
  path: mongodb://183.98.70.23/etrade #mongodb://183.98.70.23/etrade #'mongodb://localhost/etrade' #'mongodb://lmo0317.iptime.org/etrade'
cron:
  FIND_TRADING_BEST : '30 */20 9-18 * * 1-5'
  FIND_TRADING_FAVORITE : '30 */5 9-18 * * 1-5'
  SEND_TRADING_FAVORITE : '0 */1 9-18 * * 1-5'
log:
  level: 'low' #high: everything log save, middle: eventlog, error log save, low: error log save